version: "3"

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db

  # analysis-service:
  #   build:
  #     context: ./analysis-service
  #     dockerfile: Dockerfile
  #   image: analysis-service
  #   ports:
  #     - "5001:5001"
  #   env_file: ./analysis-service/.env
